version: 0.2


phases:
    install:
      commands:
        - echo "Installing kubectl..."
        - curl -o kubectl https://amazon-eks.s3.eu-west-2.amazonaws.com/1.29.0/2024-01-04/bin/linux/amd64/kubectl
        - chmod +x kubectl
        - mv kubectl /usr/local/bin/
        - echo "Installing Helm..."
        - curl -LO https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz
        - tar -zxvf helm-v3.12.0-linux-amd64.tar.gz
        - mv linux-amd64/helm /usr/local/bin/
        - helm version

    pre_build:
      commands:
        - aws ecr get-login-password --region $AWS_REGION |
          docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
        - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        - IMAGE_URI=$ECR_REPOSITORY_URI:$COMMIT_HASH

    build:
      commands:
        - docker build -t $IMAGE_URI .
        - docker push $IMAGE_URI

    post_build:
      commands:
        - aws eks update-kubeconfig --region $AWS_REGION --name counter-eks
        - helm upgrade --install counter ./helm --namespace prod --create-namespace --set image.repository=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/counter-app-ecr --set image.tag=$COMMIT_HASH
